server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

